export const amenitiesCategories = {
  "Room & Comfort": [
    "Air conditioning",
    "Flat-screen TV",
    "Hair dryer",
    "In-room safe",
    "Desk",
    "Blackout curtains",
    "Soundproofing",
    "Sofa bed",
    "Wardrobe",
    "Ceiling fan",
    "Electric kettle",
    "Ironing facilities",
    "Telephone",
    "Toiletries",
    "Bathrobe",
    "Slippers",
    "Pillow menu",
    "Premium bedding",
    "Down pillows",
    "Pillow-top mattress",
  ],
  Bathroom: [
    "Private bathroom",
    "Shared bathroom",
    "Bathtub",
    "Shower",
    "Bidet",
    "Hair dryer",
    "Toilet paper",
    "Raised toilet",
    "Accessible shower",
    "Shower seat",
    "Foot bath",
    "Jacuzzi bathtub",
    "Oversized bathtub",
    "Rain shower",
    "Hydromassage shower",
  ],
  "Dining & Kitchen": [
    "Breakfast buffet",
    "Continental breakfast",
    "Full breakfast",
    "Minibar",
    "Refrigerator",
    "Freezer",
    "Microwave",
    "Oven",
    "Stovetop",
    "Dining area",
    "Dining table",
    "Kitchen",
    "Kitchenette",
    "Cooking utensils",
    "Dishwasher",
    "Coffee/tea maker",
    "Espresso machine",
    "Children's dishware",
    "Packed lunches",
    "Special diet meals",
  ],
  "Services & Facilities": [
    "24-hour reception",
    "24-hour security",
    "Concierge service",
    "Room service",
    "Laundry service",
    "Ironing service",
    "Turndown service",
    "Luggage storage",
    "Express check-in/out",
    "Private check-in/out",
    "Currency exchange",
    "ATM on site",
    "Business center",
    "Fax/photocopying",
    "Tour information",
    "Ticket service",
    "Wedding services",
    "Babysitting/child services",
    "In-room childcare",
    "Massage",
    "Spa treatments",
  ],
  Accessibility: [
    "Wheelchair accessible",
    "Accessible parking",
    "Elevator",
    "Upper floors accessible by elevator",
    "Ground floor unit",
    "Wheelchair accessible unit",
    "Braille signs",
    "Tactile signs",
    "Hearing aids",
    "Low sink",
    "Low bathroom sink",
    "Bathroom emergency pull cord",
    "Toilet with grab rails",
    "Service animals allowed",
    "Assistance animals exempt from fees",
  ],
  "Outdoor & Recreation": [
    "Outdoor pool",
    "Indoor pool",
    "Infinity pool",
    "Kids pool",
    "Pool bar",
    "Pool cabana",
    "Pool beach towels",
    "Sun loungers",
    "Sun umbrellas",
    "Garden",
    "Terrace",
    "BBQ facilities",
    "Picnic area",
    "Playground",
    "Tennis court",
    "Golf course",
    "Bike rental",
    "Bike parking",
    "Secure bike storage",
    "Beach access",
  ],
  "Wellness & Spa": [
    "Spa",
    "Wellness center",
    "Sauna",
    "Steam bath",
    "Hot tub",
    "Massage",
    "Full body massage",
    "Couples massage",
    "Head massage",
    "Foot massage",
    "Back massage",
    "Neck massage",
    "Hand massage",
    "Facial treatments",
    "Body scrub",
    "Manicure",
    "Pedicure",
    "Hair/beauty salon",
    "Solarium",
    "Yoga",
  ],
  Entertainment: [
    "Cable TV",
    "Satellite TV",
    "Smart TV",
    "Streaming services",
    "Movies",
    "Books",
    "Board games",
    "Game room",
    "Karaoke",
    "Live music",
    "Nightclub/DJ",
    "Billiards",
    "Darts",
    "Table tennis",
    "Library",
    "Kids club",
    "Supervised kids activities",
    "Children's books",
    "Toys",
    "Kids games",
  ],
  "Safety & Security": [
    "24-hour security",
    "Fire extinguisher",
    "Smoke detector",
    "Security alarm",
    "In-room safe",
    "Front desk safe",
    "Laptop safe",
    "Outdoor surveillance",
    "Indoor surveillance",
    "Secure parking",
    "Long-term parking",
    "Valet parking",
  ],
  "Business & Technology": [
    "Business center",
    "Conference rooms",
    "Computer workstation",
    "Laptop-friendly workspace",
    "LAN",
    "WiFi",
    "Fax/photocopying",
    "Meeting/banquet facilities",
    "Business hotel",
    "Express check-in/out",
  ],
  Transportation: [
    "Airport shuttle",
    "Local area shuttle",
    "Station shuttle",
    "Ferry shuttle",
    "Shuttle service",
    "Car rental",
    "Bike rental",
    "Bike tours",
    "Bike parking",
    "Secure bike storage",
  ],
  Sustainability: [
    "Renewable energy",
    "Energy reduction measures",
    "Water saving bathroom fixtures",
    "Food waste reduction program",
    "Recycling",
    "Limited single-use plastic",
    "Investment in local sustainability",
    "Carbon offset certificates",
    "Locally sourced food",
    "Organic food",
  ],
  Pets: [
    "Pets allowed",
    "Pet friendly hotel",
    "Pet bowl",
    "Pet basket",
    "Dog run area",
    "Dogs only",
    "Dogs and cats only",
    "Service animals only",
  ],
} as const;

// Mapping from snake_case to clean names
export const amenityNameMapping: Record<string, Amenity> = {
  limited_room_service: "Room service",
  limited_room_cleaning: "Room service",
  room_service_meals_available: "Room service",
  in_room_air_conditioning: "Air conditioning",
  individually_controlled_air_conditioning: "Air conditioning",
  air_conditioning_in_all_rooms: "Air conditioning",
  flat_screen_tv: "Flat-screen TV",
  in_room_safe: "In-room safe",
  front_desk_safe: "Front desk safe",
  laptop_safe: "Laptop safe",
  hair_dryer: "Hair dryer",
  ironing_facilities: "Ironing facilities",
  ironing_service: "Ironing service",
  turndown_service: "Turndown service",
  private_bathroom: "Private bathroom",
  shared_bathroom: "Shared bathroom",
  bathtub_or_shower: "Bathtub",
  bathtub_shower_combination: "Bathtub",
  shower_seat: "Shower seat",
  accessible_shower: "Accessible shower",
  raised_toilet: "Raised toilet",
  toilet_with_grab_rails: "Toilet with grab rails",
  bathroom_emergency_pull_cord: "Bathroom emergency pull cord",
  low_sink: "Low sink",
  low_bathroom_sink: "Low bathroom sink",
  breakfast_buffet: "Breakfast buffet",
  continental_breakfast: "Continental breakfast",
  full_breakfast: "Full breakfast",
  minibar: "Minibar",
  refrigerator: "Refrigerator",
  freezer: "Freezer",
  microwave: "Microwave",
  oven: "Oven",
  stovetop: "Stovetop",
  dining_area: "Dining area",
  dining_table: "Dining table",
  kitchen: "Kitchen",
  kitchenette: "Kitchenette",
  cooking_utensils: "Cooking utensils",
  dishwasher: "Dishwasher",
  tea_coffee_maker: "Coffee/tea maker",
  espresso_machine: "Espresso machine",
  childrens_dishware: "Children's dishware",
  packed_lunches: "Packed lunches",
  special_diet_meals: "Special diet meals",
  twenty_four_hour_reception: "24-hour reception",
  twenty_four_hour_security_staff: "24-hour security",
  concierge_service: "Concierge service",
  room_service: "Room service",
  laundry_service: "Laundry service",
  luggage_storage: "Luggage storage",
  express_check_in_out: "Express check-in/out",
  private_check_in_out: "Private check-in/out",
  currency_exchange: "Currency exchange",
  atm_on_site: "ATM on site",
  business_center: "Business center",
  fax_photocopying: "Fax/photocopying",
  tour_information: "Tour information",
  ticket_service: "Ticket service",
  wedding_services: "Wedding services",
  babysitting_child_services: "Babysitting/child services",
  in_room_childcare: "In-room childcare",
  wheelchair_accessible: "Wheelchair accessible",
  accessible_parking: "Accessible parking",
  elevator: "Elevator",
  upper_floors_accessible_by_elevator: "Upper floors accessible by elevator",
  ground_floor_unit: "Ground floor unit",
  wheelchair_accessible_unit: "Wheelchair accessible unit",
  braille_signs: "Braille signs",
  tactile_signs: "Tactile signs",
  hearing_aids: "Hearing aids",
  service_animals_only: "Service animals only",
  assistance_animals_exempt_from_fees_or_restrictions:
    "Assistance animals exempt from fees",
  outdoor_pool: "Outdoor pool",
  indoor_pool: "Indoor pool",
  infinity_pool: "Infinity pool",
  kids_pool: "Kids pool",
  pool_bar: "Pool bar",
  pool_cabana: "Pool cabana",
  pool_beach_towels: "Pool beach towels",
  sun_loungers_beach_chairs: "Sun loungers",
  sun_umbrellas: "Sun umbrellas",
  garden: "Garden",
  terrace: "Terrace",
  bbq_facilities: "BBQ facilities",
  picnic_area: "Picnic area",
  playground: "Playground",
  tennis_court: "Tennis court",
  golf_course_within_3km: "Golf course",
  bike_rental: "Bike rental",
  bike_parking: "Bike parking",
  secure_bike_storage: "Secure bike storage",
  beach: "Beach access",
  spa_wellness_center: "Spa",
  wellness_center: "Wellness center",
  sauna: "Sauna",
  steam_bath: "Steam bath",
  hot_tub: "Hot tub",
  hot_tub_jacuzzi: "Hot tub",
  massage: "Massage",
  full_body_massage: "Full body massage",
  couples_massage: "Couples massage",
  head_massage: "Head massage",
  foot_massage: "Foot massage",
  back_massage: "Back massage",
  neck_massage: "Neck massage",
  hand_massage: "Hand massage",
  facial_treatments: "Facial treatments",
  body_scrub: "Body scrub",
  manicure: "Manicure",
  pedicure: "Pedicure",
  hair_beauty_salon: "Hair/beauty salon",
  solarium: "Solarium",
  yoga: "Yoga",
  cable_tv: "Cable TV",
  satellite_tv: "Satellite TV",
  smart_tv: "Smart TV",
  streaming_services: "Streaming services",
  movies: "Movies",
  books: "Books",
  board_games_puzzles: "Board games",
  game_room: "Game room",
  karaoke: "Karaoke",
  live_music_performance: "Live music",
  nightclub_dj: "Nightclub/DJ",
  billiards: "Billiards",
  darts: "Darts",
  table_tennis: "Table tennis",
  library: "Library",
  kids_club: "Kids club",
  supervised_kids_activities: "Supervised kids activities",
  childrens_books: "Children's books",
  toys: "Toys",
  kids_games: "Kids games",
  fire_extinguisher: "Fire extinguisher",
  smoke_detector: "Smoke detector",
  security_alarm: "Security alarm",
  outdoor_surveillance: "Outdoor surveillance",
  indoor_surveillance: "Indoor surveillance",
  secure_parking: "Secure parking",
  long_term_parking: "Long-term parking",
  valet_parking: "Valet parking",
  computer_workstation: "Computer workstation",
  laptop_friendly_workspace: "Laptop-friendly workspace",
  lan: "LAN",
  wifi: "WiFi",
  conference_event_rooms: "Conference rooms",
  meeting_banquet_facilities: "Meeting/banquet facilities",
  business_hotel: "Business hotel",
  airport_shuttle: "Airport shuttle",
  local_area_shuttle: "Local area shuttle",
  station_shuttle: "Station shuttle",
  ferry_shuttle: "Ferry shuttle",
  shuttle_service: "Shuttle service",
  car_rental: "Car rental",
  bike_tours: "Bike tours",
  renewable_energy_used: "Renewable energy",
  energy_reduction_measures: "Energy reduction measures",
  water_saving_bathroom_fixtures: "Water saving bathroom fixtures",
  food_waste_reduction_program: "Food waste reduction program",
  recycling: "Recycling",
  limited_single_use_plastic_items: "Limited single-use plastic",
  investment_in_local_sustainability_projects:
    "Investment in local sustainability",
  carbon_offset_certificates: "Carbon offset certificates",
  locally_sourced_food: "Locally sourced food",
  organic_food: "Organic food",
  pets_allowed: "Pets allowed",
  pet_friendly_hotel: "Pet friendly hotel",
  pet_bowl: "Pet bowl",
  pet_basket: "Pet basket",
  dog_run_area: "Dog run area",
  dogs_only: "Dogs only",
  dogs_and_cats_only: "Dogs and cats only",
};

// Utility function to convert snake_case amenity name to clean name
export function getCleanAmenityName(
  snakeCaseName: string
): Amenity | undefined {
  return amenityNameMapping[snakeCaseName];
}

export type AmenityCategory = keyof typeof amenitiesCategories;
export type Amenity = (typeof amenitiesCategories)[AmenityCategory][number];
